server:
  port: 8084

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5544/order_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

services:
  inventory-url: ${INVENTORY_SERVICE_URL:http://localhost:8083}
  payment-url: ${PAYMENT_SERVICE_URL:http://localhost:8085}
