server:
  port: 8083

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5544/inventory_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
